// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_Rnanoflann_RCPPEXPORTS_H_GEN_
#define RCPP_Rnanoflann_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace Rnanoflann {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("Rnanoflann", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("Rnanoflann", "_Rnanoflann_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in Rnanoflann");
            }
        }
    }

    inline List knn(arma::mat data, arma::mat points, arma::uword k, const std::string search = "standard", const double eps = 0.0, const bool sorted = false, const double radius = 0.0, const bool parallel = false) {
        typedef SEXP(*Ptr_knn)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_knn p_knn = NULL;
        if (p_knn == NULL) {
            validateSignature("List(*knn)(arma::mat,arma::mat,arma::uword,const std::string,const double,const bool,const double,const bool)");
            p_knn = (Ptr_knn)R_GetCCallable("Rnanoflann", "_Rnanoflann_knn");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_knn(Shield<SEXP>(Rcpp::wrap(data)), Shield<SEXP>(Rcpp::wrap(points)), Shield<SEXP>(Rcpp::wrap(k)), Shield<SEXP>(Rcpp::wrap(search)), Shield<SEXP>(Rcpp::wrap(eps)), Shield<SEXP>(Rcpp::wrap(sorted)), Shield<SEXP>(Rcpp::wrap(radius)), Shield<SEXP>(Rcpp::wrap(parallel)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<List >(rcpp_result_gen);
    }

}

#endif // RCPP_Rnanoflann_RCPPEXPORTS_H_GEN_
